version: '3'

services:
    mysql:
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ~/docker/mysql8/:/var/lib/mysql/
        networks:
            - dev
    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - mysql
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 300M
        networks:
            - dev
    php:
        image: php-83
        command: "symfony server:start"
        restart: unless-stopped
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:8000
        networks:
            - dev
    messenger:
        image: php-83
        command: "php bin/console messenger:consume async --limit=2"
        restart: unless-stopped
        volumes:
            - ./:/var/www/html/
        networks:
            - dev
    maildev:
        image: maildev/maildev
        restart: unless-stopped
        ports:
            - 1080:1080
            - 1025:1025
        networks:
            - dev
networks:
    dev:
