auth:
    resource: ../src/Http/Auth/Controller/
    type: attribute
    prefix: /authentification
    name_prefix: auth_

admin:
    resource: ../src/Http/Admin/Controller/
    type: attribute
    name_prefix: admin_
    prefix: administration
